from numbsys.numbsys import isbinary
from numbsys.numbsys import isoctal
from numbsys.numbsys import ishexadecimal
from numbsys.numbsys import dtob
from numbsys.numbsys import dtoo
from numbsys.numbsys import dtoh
from numbsys.numbsys import btod
from numbsys.numbsys import otod
from numbsys.numbsys import htod
from numbsys.numbsys import htoo
from numbsys.numbsys import btoo
from numbsys.numbsys import htob
from numbsys.numbsys import btoh
from numbsys.numbsys import otob
from numbsys.numbsys import otoh
from numbsys.numbsys import binadd
from numbsys.numbsys import binsub
from numbsys.numbsys import octadd
from numbsys.numbsys import octsub
from numbsys.numbsys import hexadd
from numbsys.numbsys import hexsub
from numbsys.numbsys import decadd
from numbsys.numbsys import decsub
