from numsys import isbinary
from numsys import isoctal
from numsys import ishexadecimal
from numsys import dtob
from numsys import dtoo
from numsys import dtoh
from numsys import btod
from numsys import otod
from numsys import htod
from numsys import htoo
from numsys import btoo
from numsys import htob
from numsys import btoh
from numsys import otob
from numsys import otoh
from numsys import binadd
from numsys import binsub
from numsys import octadd
from numsys import octsub
from numsys import hexadd
from numsys import hexsub
from numsys import decadd
from numsys import decsub
